language: objective-c
osx_image: xcode9

before_script:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

script:
    - xcodebuild clean build -sdk iphonesimulator -workspace R9HTTPRequest.xcworkspace -scheme R9HTTPRequest CODE_SIGNING_REQUIRED=NO