language: objective-c
osx_image: xcode9

addons:
  ssh_known_hosts: git.example.com

script:
    - xcodebuild clean build -sdk iphonesimulator -workspace R9HTTPRequest.xcworkspace -scheme R9HTTPRequest CODE_SIGNING_REQUIRED=NO