language: objective-c
osx_image: xcode9

before_install:
  - gem install xcpretty
  - pod repo update

script:
    - xcodebuild clean build -sdk iphonesimulator -workspace R9HTTPRequest.xcworkspace -scheme R9HTTPRequest CODE_SIGNING_REQUIRED=NO | xcpretty